### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by Ychop** [HenrikaSandberg/weatherapp#1]
- [x] komplette Datum bei Vorschau (Detailansicht)
- [x] Detailansicht - hinter Stadt auch Landeskürzel
- [x] Max/Min temp bei Detailansicht muss falsch sein xD
- [x] Detail auf zurück … man landet immer bei Berlin
- [x] Sunrise / Sunset Zeitzone richtig anzeigen (Icons)
- [x] Suchleiste Vorschläge siehe Johannes Mail -> als weitere Komponente
- [x] verschiedene Hintergrundbilder anzeigen lassen

**Comment by Ychop** [comment]
Die Ganzen Zeiten, also sun set und sunrise sind die Localen Zeiten die hier bei uns sind GMT+1
