### ISSUE TITLE
New ToDo's

### ISSUE THREAD

**Issue by HenrikaSandberg** [HenrikaSandberg/weatherapp#2]
- [x] - Detailansicht bei Today nur Max Temp anzeigen (Detailansicht bei Forecaste beides anzeigen)
- [x] - Uhrzeit bei Detail Forecast muss weg!
- [x] - Suchleiste: Nur nach Anfangsbuchstaben filtern
- [x] - Anfangs Today auswählen (auch farblich hervorheben)
- [x] - Detailansicht Zeit nicht 12:00:00 sondern als 12:00 GMT anzeigen
- [x] - verschiedene Hintergrundbilder anzeigen lassen
